#!/bin/bash
# @IMPORTANT - you MUST create  the file private/vars with the following content:
# export MYSQL_PW="{password}"
# Include private variables
./private/vars
# Run docker image
docker run -p 8086:3306 \
-v ./data/mysql:/var/lib/mysql \
-e MYSQL_ROOT_PASSWORD=$MYSQL_PW \
--name=wp-mysql \
-d uchilaka/wp-mysql:dev