#!/bin/bash
# @IMPORTANT - you MUST create  the file private/vars with the following content:
# export MYSQL_PW="{password}"
WDIR=$(echo ~/Developer/Docker/wp-mysql)
if ! [ -d $WDIR ]; then 
    WDIR = "/opt/containers/wp-mysql"
fi
#WDIR=$(pwd)
DATADIR=$WDIR/data/mysql
CONF=$WDIR/private/vars.conf 
LOGFILE=$(pwd)/logs/$(date "+%Y%m%d_%H00").txt
PRIVDIR=$WDIR/private

if ! [ -f $CONF ]; then 
    # Create config file 
    if ! [ -d $PRIVDIR ]; then 
        logger -s "Creating $PRIVDIR..."
        mkdir $PRIVDIR
    fi 
    cp $WDIR/vars-sample.conf $PRIVDIR/vars.conf
fi

# Make sure directory for mysql data exists
if ! [ -d $DATADIR ]; then 
    mkdir -p $DATADIR
fi

if [ -z $MYSQL_INSTANCE_NAME ]; then 
    MYSQL_INSTANCE_NAME="wp-mysql"
fi

# Include private variables
source $CONF

# Run docker image
docker run -p 8086:3306 \
-v $DATADIR:/var/lib/mysql \
-e MYSQL_ROOT_PASSWORD=$MYSQL_PW \
--name=$MYSQL_INSTANCE_NAME \
--restart unless-stopped \
-d uchilaka/wp-mysql:dev
